service: default
runtime: go111
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /
  secure: always
  static_files: static/index.html
  upload: static/index.html
- url: /new-version
  secure: always
  static_files: static/new-version.html
  upload: static/new-version.html
- url: /static
  secure: always
  static_dir: static
- url: /admin/.*
  secure: always
  login: admin
  script: auto
- url: /.*
  secure: always
  script: auto